export const CyberDrake = {
  level: 1,
  health: 100,
  maxHealth: 100,
  attack: 35,
  defense: 30,
  speed: 42,
  luck: 25,
  specialAttack: 60,
  specialDefense: 32,
  experience: 0,
  name: "Cyber Drake",
  userId: "",
  type: "Digital Warrior",
  image: "/players/cyber-drake.png",
};

export const PixelWyrm = {
  level: 1,
  health: 100,
  maxHealth: 100,
  attack: 32,
  defense: 35,
  speed: 38,
  luck: 28,
  specialAttack: 57,
  specialDefense: 35,
  experience: 0,
  name: "Pixel Wyrm",
  userId: "",
  type: "Code Ninja",
  image: "/players/pixel-wyrm.png",
};

export const QuantumSphinx = {
  level: 1,
  health: 100,
  maxHealth: 100,
  attack: 40,
  defense: 34,
  speed: 35,
  luck: 22,
  specialAttack: 65,
  specialDefense: 38,
  experience: 0,
  name: "Quantum Sphinx",
  userId: "",
  type: "AI Mastermind",
  image: "/players/quantum-sphinx.png",
};

export const DataGolem = {
  level: 1,
  health: 100,
  maxHealth: 100,
  attack: 30,
  defense: 40,
  speed: 30,
  luck: 20,
  specialAttack: 55,
  specialDefense: 42,
  experience: 0,
  name: "Data Golem",
  userId: "",
  type: "Digital Guardian",
  image: "/players/data-golem.png",
};

export const ByteSerpent = {
  level: 1,
  health: 100,
  maxHealth: 100,
  attack: 42,
  defense: 28,
  speed: 47,
  luck: 34,
  specialAttack: 62,
  specialDefense: 30,
  experience: 0,
  name: "Byte Serpent",
  userId: "",
  type: "Code Champion",
  image: "/players/byte-serpent.png",
};
